### PR TITLE
Generalize necessary changes for MTC to work for MetCouncil and other agencies into the future

### PR DESCRIPTION
**Pull request by e-lo**
Closes Issue #229 

1. store "best" default parameters for each class; stored at class-level
2. update methods to be able to override default parameters

### CODE REVIEW

**Comment by lmz** [comment]
Hello - is it possible to prioritize this PR? I'm concerned that the distance between `generic_agency` and `develop` are widening. Since we use `generic_agency`, if I add a feature to `develop`, it may be difficult to merge it into `generic_agency` for our own use if these branches are too different.  Thanks!

**Comment by lmz** [comment]
Hi again, @DavidOry , @i-am-sijia and @e-lo -- Just pinging on this again; what's the plan/timeline?  Thank you!

**Comment by DavidOry** [comment]
> Hi again, @DavidOry , @i-am-sijia and @e-lo -- Just pinging on this again; what's the plan/timeline? Thank you!

Yes. Discussed this morning with @e-lo. What's your best guess at a timeline @e-lo?

**Comment by e-lo** [comment]
CLosing this as having been superceeded by work in `selection-refactor` branch.

**Pull request closed without merging**
