### PR TITLE
Implement functionality for project card to dictate how to handle sco…

### LINKED ISSUE #373: Overwrite scoped property feature isn't propagated from project card
## Describe the bug
There are two project cards making managed lane changes on the same link. The one applied later cannot overwrite the existing values, causing an error at [_resolve_conflicting_scopes](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/network_wrangler/roadway/links/edit.py#L184)

```python 
ValidationError: 1 validation error for _resolve_conflicting_scopes
1
  Input should be a valid dictionary or instance of IndivScopedPropertySetItem [type=model_type, input_value=ScopedPropertySetList(roo...sting=None, change=-1)]), input_type=ScopedPropertySetList]
```

## Cause

`edit_link_property()` describes and uses, but doesn't take as an input `overwrite_all_scoped` and `overwrite_conflicting_scoped`.  Need to propagate these settings from project card. 

## Resolution

1. Implement functionality in ProjectCard to control functionality: see https://github.com/network-wrangler/projectcard/issues/32
2. Propagate project card info to `edit_link_property()`

### PR DESCRIPTION
**Pull request by e-lo**
Fixes #373 as described in that issue. Associated required issue: https://github.com/network-wrangler/projectcard/issues/32

### CODE REVIEW

**Comment by e-lo** [comment]
TODO:

- [ ] Add `overwrite_conflicting` bool arg to apply()

**Comment by e-lo** [comment]
@yueshuaing and @i-am-sijia please confirm this is implemented as desired

**Comment by e-lo** [comment]
@yueshuaing and @i-am-sijia please confirm if this approach looks GTG and i can resolve conflicts and merge.

**Comment by i-am-sijia** [comment]
> @yueshuaing and @i-am-sijia please confirm if this approach looks GTG and i can resolve conflicts and merge.

Yue tested it and it did not work, I was referring to it in my email as the two managed lane project cards case. @yueshuaing can you please provide error message?

**Comment by e-lo** [comment]
I'll see if resolving the conflicting files will help...

**Comment by yueshuaing** [comment]
> > @yueshuaing and @i-am-sijia please confirm if this approach looks GTG and i can resolve conflicts and merge.
> 
> Yue tested it and it did not work, I was referring to it in my email as the two managed lane project cards case. @yueshuaing can you please provide error message?

The error message is similar to last time. Seems that the validation step requires a specific datatype `dictionary` or `IndivScopedPropertySetItem`, but the input is `ScopedPropertySetList`
```python
validation error for _resolve_conflicting_scopes
1
Input should be a valid dictionary or instance of IndivScopedPropertySetItem [type=model_type, input_value=ScopedPropertySetList(root=[ScopedPropertySetList(...icts=False, change=-1)]), input_type=ScopedPropertySetList]
```

**Comment by i-am-sijia** [comment]
Here is an example in Rachel's workflow:

There is a base year MnPass managed lane project card add ML for link 35474:
https://github.com/Metropolitan-Council/project_card_registry/blob/378196713303be5568d2340812f90c435b232e6c/projects/BaseMnPASS/394_EB_MnPASS.yml#L39

There is a future year MnPass managed lane project card that expands link 35474 and its ML:
https://github.com/Metropolitan-Council/project_card_registry/blob/Test1_converted_project_cards/projects/NoBuild_MnPASS2023/394_louisiana_ave_option2.yml

Both of these project cards will be applied to link 35474 in future year scenario. Would it be an issue? We will test it out.

@e-lo I thought this PR is to address use cases like this. Maybe I'm wrong? @yueshuaing will test applying these two projects with this PR.

**Comment by e-lo** [comment]
Found the issue using the test – I didn't appropriately handle the case where there were existing scoped link entries but where none were conflicting and they were all matching and implementing a change (not set).  Working to fix now.

**Comment by e-lo** [comment]
I think this can be safely merged at this point.

**Comment by yueshuaing** [comment]
I've tested the two project cards @i-am-sijia mentioned above, confirming it is working fine now!

**Pull request merged**
