### PR TITLE
Moved documentation from sphinx to mkdocs

### LINKED ISSUE #316: [Chore] Migrate from sphinx to mkdocs
### User Story
*As a developer who wants to work with a limited set of technologies, I'd like to use mkdocs which I use across more projects.*

### Priority 
Medium

### Level of Effort
Low

### Resolution Ideas
Copy mkdocs/mike items from `tm2py`

### PR DESCRIPTION
**Pull request by e-lo**
Also:
- updated contributing directions
- added contributor list

Fixes #316

### CODE REVIEW

**Comment by e-lo** [comment]
All of your suggestions are great @lmz but they aren't part of this specific PR as they are addressed in many of the others...

**Comment by lmz** [comment]
I know, sorry!  I was just trying to get it to run :p

**Comment by e-lo** [comment]
@lmz - should run ok now!

**Review by lmz — APPROVED** [review]
Woot - looks good to me!
I made a few small changes -- and I'd like to explore issue #278 next... 😉

**Pull request merged**
