### PR TITLE
changes from MTC implementation

### PR DESCRIPTION
**Pull request by i-am-sijia**

### CODE REVIEW

**Comment by e-lo** [comment]
Can you please add "issues" that each of these changes addresses?

**Comment by lmz** [comment]
Requesting this PR be prioritized as well, for the same reason discussed in https://github.com/wsp-sag/network_wrangler/pull/236#issuecomment-1034034250.  Thanks!

**Comment by i-am-sijia** [comment]
@e-lo this PR has MTC's changes to apply their transit project cards. I will add some description shortly.

**Comment by e-lo** [comment]
@yueshuaing and @i-am-sijia : I believe this PR is now moot and can be closed?

If there are any remaining items, please:

1. add an issue
2. create a test in `selection refactor` branch that if passes, will close this issue.

**Pull request closed without merging**
